name: Generate Pacman Animation

on:
  schedule: # Uruchamiaj codziennie o północy
    - cron: "0 0 * * *"
  workflow_dispatch: # Pozwala odpalić akcję ręcznie w dowolnej chwili
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman SVG
        uses: abhisheknaiidu/pacman-contribution-graph@master
        with:
          github_user_name: ${{ github.repository_owner }}
          output_branch: pacman-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
